name: GriefPreventionDynmapReborn
main: com.samoatesgames.griefpreventiondynmapreborn.GriefPreventionDynmap
version: 1.1
authors: [SamOatesPlugins, Darklust]
depend: [ dynmap, GriefPrevention ]
description: Render GriefPrevention claims on a dynamp.
commands:
  setgpname:
    usage: "/setgpname <name>"
    description: "Sets the name of a GP claim"
    permission: gpd.setname
  removegpname:
    usage: "/removegpname"
    description: "Removes the custom name of a GP claim"
    permission: gpd.removename
permissions:
  gpd.setname:
    description: Grants ability to set name of GP claims
    default: op
  gpd.removename:
    description: Grants ability to remove name of GP claims
    default: op